"""
Qt Core Abstractions Simulator: QObject, moc Meta-Object System, Signals & Slots, Event Loop, and Declarative Property Bindings.

This zero-dependency Python reconstruction simulates the foundational computational mechanics of Qt:
1. QObject ownership trees and deterministic parent-child memory management.
2. The Meta-Object System (moc) exposing runtime class introspection, dynamic properties, and invokables.
3. Decoupled Signals and Slots communication supporting Direct and Queued dispatch modes.
4. Centralized Event Loop dispatch with event filters.
5. Declarative QML-style reactive property bindings over QObject properties.
"""

from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Set, Tuple


class ConnectionType(Enum):
    DIRECT = 1
    QUEUED = 2


class QEvent:
    """Base class for all Qt event objects."""
    def __init__(self, event_type: str, data: Any = None):
        self.type = event_type
        self.data = data
        self.accepted = False

    def accept(self):
        self.accepted = True

    def ignore(self):
        self.accepted = False


class QMetaObject:
    """
    Simulates the static metadata generated by the Meta-Object Compiler (moc) for a QObject subclass.
    """
    def __init__(self, class_name: str, super_class: Optional['QMetaObject'] = None):
        self.class_name = class_name
        self.super_class = super_class
        self.properties: Set[str] = set()
        self.signals: Set[str] = set()
        self.slots: Set[str] = set()

    def add_property(self, name: str):
        self.properties.add(name)

    def add_signal(self, name: str):
        self.signals.add(name)

    def add_slot(self, name: str):
        self.slots.add(name)

    def inherits(self, class_name: str) -> bool:
        if self.class_name == class_name:
            return True
        if self.super_class:
            return self.super_class.inherits(class_name)
        return False


class Signal:
    """
    Signal descriptor modeling type-aware signal emission and slot binding.
    """
    def __init__(self, name: str, *arg_types: type):
        self.name = name
        self.arg_types = arg_types

    def __get__(self, instance, owner):
        if instance is None:
            return self
        if self.name not in instance._signal_connections:
            instance._signal_connections[self.name] = []
        return BoundSignal(instance, self.name, self.arg_types)


class BoundSignal:
    """A signal bound to a specific QObject instance."""
    def __init__(self, instance: 'QObject', name: str, arg_types: Tuple[type, ...]):
        self.instance = instance
        self.name = name
        self.arg_types = arg_types

    def connect(self, slot: Callable, connection_type: ConnectionType = ConnectionType.DIRECT):
        self.instance._connect_signal(self.name, slot, connection_type)

    def disconnect(self, slot: Optional[Callable] = None):
        self.instance._disconnect_signal(self.name, slot)

    def emit(self, *args):
        # Validate type arguments if provided
        if self.arg_types and len(args) != len(self.arg_types):
            raise TypeError(f"Signal '{self.name}' expects {len(self.arg_types)} arguments, got {len(args)}")

        self.instance._emit_signal(self.name, args)


class QObject:
    """
    Core object model providing hierarchical parent-child ownership,
    dynamic properties, signal-slot connections, and event filtering.
    """
    meta_object = QMetaObject("QObject")

    def __init__(self, parent: Optional['QObject'] = None, name: str = ""):
        self._object_name = name or self.__class__.__name__
        self._parent: Optional['QObject'] = None
        self._children: List['QObject'] = []
        self._dynamic_properties: Dict[str, Any] = {}
        self._property_bindings: Dict[str, Callable[[], Any]] = {}
        self._signal_connections: Dict[str, List[Tuple[Callable, ConnectionType]]] = {}
        self._event_filters: List['QObject'] = []
        self._destroyed = False

        if parent is not None:
            self.set_parent(parent)

    def object_name(self) -> str:
        return self._object_name

    def set_object_name(self, name: str):
        self._object_name = name

    def parent(self) -> Optional['QObject']:
        return self._parent

    def children(self) -> List['QObject']:
        return list(self._children)

    def set_parent(self, parent: Optional['QObject']):
        if self._parent == parent:
            return
        if self._parent is not None:
            if self in self._parent._children:
                self._parent._children.remove(self)
        self._parent = parent
        if self._parent is not None:
            self._parent._children.append(self)

    def delete_later(self):
        """Schedules object for destruction in the event loop."""
        QCoreApplication.post_event(self, QEvent("DeferredDelete"))

    def destroy(self):
        """Recursively destroys all children and unbinds parent connections."""
        if self._destroyed:
            return

        # Destroy children first (bottom-up tree destruction)
        for child in list(self._children):
            child.destroy()
        self._children.clear()

        # Detach from parent
        if self._parent is not None and self in self._parent._children:
            self._parent._children.remove(self)
            self._parent = None

        self._destroyed = True

    # Property System
    def set_property(self, name: str, value: Any) -> bool:
        old_val = self._dynamic_properties.get(name)
        self._dynamic_properties[name] = value

        # Check for property bindings dependent on this property
        self._update_dependent_bindings(name)

        # Notify if property changed signal exists
        signal_name = f"{name}Changed"
        if signal_name in self._signal_connections:
            self._emit_signal(signal_name, (value,))

        return old_val != value

    def property(self, name: str) -> Any:
        # Evaluate binding if dynamic binding exists
        if name in self._property_bindings:
            return self._property_bindings[name]()
        return self._dynamic_properties.get(name, None)

    def set_binding(self, name: str, binding_func: Callable[[], Any]):
        """Sets a declarative reactive property binding (QML style)."""
        self._property_bindings[name] = binding_func
        # Evaluate initial value
        val = binding_func()
        self.set_property(name, val)

    def _update_dependent_bindings(self, updated_property_name: str):
        for prop_name, binding_func in list(self._property_bindings.items()):
            try:
                new_val = binding_func()
                if self._dynamic_properties.get(prop_name) != new_val:
                    self._dynamic_properties[prop_name] = new_val
                    signal_name = f"{prop_name}Changed"
                    if signal_name in self._signal_connections:
                        self._emit_signal(signal_name, (new_val,))
            except Exception:
                pass

    # Signals & Slots Dispatch
    def _connect_signal(self, signal_name: str, slot: Callable, connection_type: ConnectionType):
        if signal_name not in self._signal_connections:
            self._signal_connections[signal_name] = []
        self._signal_connections[signal_name].append((slot, connection_type))

    def _disconnect_signal(self, signal_name: str, slot: Optional[Callable] = None):
        if signal_name in self._signal_connections:
            if slot is None:
                self._signal_connections[signal_name].clear()
            else:
                self._signal_connections[signal_name] = [
                    (s, ct) for (s, ct) in self._signal_connections[signal_name] if s != slot
                ]

    def _emit_signal(self, signal_name: str, args: Tuple[Any, ...]):
        if signal_name not in self._signal_connections:
            return

        for slot, connection_type in list(self._signal_connections[signal_name]):
            if connection_type == ConnectionType.DIRECT:
                slot(*args)
            elif connection_type == ConnectionType.QUEUED:
                QCoreApplication.post_event(
                    self, QEvent("QueuedSignal", {"slot": slot, "args": args})
                )

    # Event System
    def install_event_filter(self, filter_obj: 'QObject'):
        if filter_obj not in self._event_filters:
            self._event_filters.append(filter_obj)

    def remove_event_filter(self, filter_obj: 'QObject'):
        if filter_obj in self._event_filters:
            self._event_filters.remove(filter_obj)

    def event_filter(self, watched: 'QObject', event: QEvent) -> bool:
        """Override in subclass to intercept events of watched objects. Returns True to stop event."""
        return False

    def event(self, event: QEvent) -> bool:
        """Main event dispatcher for this object."""
        # Check event filters first
        for filter_obj in list(self._event_filters):
            if filter_obj.event_filter(self, event):
                event.accept()
                return True

        if event.type == "DeferredDelete":
            self.destroy()
            event.accept()
            return True
        elif event.type == "QueuedSignal":
            slot = event.data["slot"]
            args = event.data["args"]
            slot(*args)
            event.accept()
            return True

        return False


class QCoreApplication:
    """
    Central event loop manager directing queued event dispatch and signal delivery.
    """
    _event_queue: List[Tuple[QObject, QEvent]] = []

    @classmethod
    def post_event(cls, receiver: QObject, event: QEvent):
        cls._event_queue.append((receiver, event))

    @classmethod
    def process_events(cls) -> int:
        """Executes one pass of the central event loop. Returns processed event count."""
        events_to_process = list(cls._event_queue)
        cls._event_queue.clear()
        processed = 0

        for receiver, event in events_to_process:
            if not receiver._destroyed:
                receiver.event(event)
                processed += 1

        return processed

    @classmethod
    def clear(cls):
        cls._event_queue.clear()
