"""
FFmpeg Multimedia Pipeline, Library Decomposition & CLI Substrate Simulator.
Demonstrates AVPacket / AVFrame dataflow across 5 processing stages (Demux -> Decode -> Filter -> Encode -> Mux),
codec/container capability registry, filter graph execution, reference-counted buffers, and CLI translation.
"""

import os
import re
from typing import Dict, List, Optional, Tuple, Any, Callable


# ============================================================================
# 1. Intermediate Data Representations & Memory Management
# ============================================================================

class AVBufferRef:
    """Simulates thread-safe, reference-counted memory buffer management (AVBufferRef)."""
    def __init__(self, size: int, data: Optional[bytes] = None):
        self.size = size
        self.data = data if data is not None else b'\x00' * size
        self.ref_count = 1

    def ref(self) -> 'AVBufferRef':
        self.ref_count += 1
        return self

    def unref(self) -> bool:
        self.ref_count -= 1
        return self.ref_count == 0


class AVPacket:
    """
    Represents a compressed bitstream unit (AVPacket).
    Generated by demuxer or encoder; consumed by decoder or muxer.
    """
    def __init__(self, stream_index: int, pts: int, dts: int, data: bytes, is_keyframe: bool = False):
        self.stream_index = stream_index
        self.pts = pts
        self.dts = dts
        self.data = data
        self.size = len(data)
        self.is_keyframe = is_keyframe
        self.buffer_ref = AVBufferRef(self.size, data)

    def clone(self) -> 'AVPacket':
        pkt = AVPacket(self.stream_index, self.pts, self.dts, self.data, self.is_keyframe)
        pkt.buffer_ref = self.buffer_ref.ref()
        return pkt


class AVFrame:
    """
    Represents an uncompressed video frame or audio sample buffer (AVFrame).
    Generated by decoder or filter; consumed by filter or encoder.
    """
    def __init__(
        self,
        width: int = 1920,
        height: int = 1080,
        pixel_format: str = "yuv420p",
        pts: int = 0,
        nb_samples: int = 0,
        sample_format: str = "fltp",
        channels: int = 2
    ):
        self.width = width
        self.height = height
        self.pixel_format = pixel_format
        self.pts = pts
        self.nb_samples = nb_samples
        self.sample_format = sample_format
        self.channels = channels

        # Calculate plane sizes
        if nb_samples > 0:
            plane_size = nb_samples * channels * 4  # Float 32-bit PCM
            self.media_type = "audio"
        else:
            plane_size = int(width * height * 1.5) if pixel_format == "yuv420p" else width * height * 3
            self.media_type = "video"

        self.planes = [b'\xFF' * plane_size]
        self.buffer_ref = AVBufferRef(plane_size, self.planes[0])

    def clone(self) -> 'AVFrame':
        frame = AVFrame(
            width=self.width,
            height=self.height,
            pixel_format=self.pixel_format,
            pts=self.pts,
            nb_samples=self.nb_samples,
            sample_format=self.sample_format,
            channels=self.channels
        )
        frame.planes = list(self.planes)
        frame.buffer_ref = self.buffer_ref.ref()
        return frame


# ============================================================================
# 2. Codec & Container Capability Registries (libavcodec & libavformat)
# ============================================================================

class CodecDescriptor:
    """Represents a registered AVCodec encoder or decoder capability."""
    def __init__(self, name: str, media_type: str, codec_id: str, supported_formats: List[str]):
        self.name = name
        self.media_type = media_type  # "video" or "audio"
        self.codec_id = codec_id      # e.g. "h264", "vp9", "aac", "mp3"
        self.supported_formats = supported_formats


class ContainerDescriptor:
    """Represents a registered AVInputFormat or AVOutputFormat container driver."""
    def __init__(self, name: str, extensions: List[str], mime_type: str, probe_score: int = 100):
        self.name = name
        self.extensions = [ext.lower() for ext in extensions]
        self.mime_type = mime_type
        self.probe_score = probe_score


class CodecContainerRegistry:
    """
    Central registration and discovery engine simulating libavcodec/libavformat table lookup.
    """
    def __init__(self):
        self.decoders: Dict[str, CodecDescriptor] = {}
        self.encoders: Dict[str, CodecDescriptor] = {}
        self.demuxers: Dict[str, ContainerDescriptor] = {}
        self.muxers: Dict[str, ContainerDescriptor] = {}
        self._register_defaults()

    def _register_defaults(self):
        # Default Decoders
        self.register_decoder(CodecDescriptor("h264_decoder", "video", "h264", ["yuv420p", "nv12"]))
        self.register_decoder(CodecDescriptor("vp9_decoder", "video", "vp9", ["yuv420p", "yuva420p"]))
        self.register_decoder(CodecDescriptor("aac_decoder", "audio", "aac", ["fltp", "s16"]))
        self.register_decoder(CodecDescriptor("mp3_decoder", "audio", "mp3", ["s16p", "fltp"]))

        # Default Encoders
        self.register_encoder(CodecDescriptor("libx264", "video", "h264", ["yuv420p", "nv12"]))
        self.register_encoder(CodecDescriptor("libvpx-vp9", "video", "vp9", ["yuv420p"]))
        self.register_encoder(CodecDescriptor("aac_encoder", "audio", "aac", ["fltp"]))
        self.register_encoder(CodecDescriptor("libmp3lame", "audio", "mp3", ["s16p"]))

        # Default Demuxers & Muxers
        self.register_demuxer(ContainerDescriptor("mov,mp4,m4a,3gp,3g2,mj2", ["mp4", "m4a", "mov"], "video/mp4", 100))
        self.register_demuxer(ContainerDescriptor("matroska,webm", ["mkv", "webm"], "video/x-matroska", 90))
        self.register_demuxer(ContainerDescriptor("mp3", ["mp3"], "audio/mpeg", 80))

        self.register_muxer(ContainerDescriptor("mp4", ["mp4"], "video/mp4"))
        self.register_muxer(ContainerDescriptor("matroska", ["mkv"], "video/x-matroska"))
        self.register_muxer(ContainerDescriptor("webm", ["webm"], "video/webm"))

    def register_decoder(self, descriptor: CodecDescriptor):
        self.decoders[descriptor.codec_id] = descriptor

    def register_encoder(self, descriptor: CodecDescriptor):
        self.encoders[descriptor.name] = descriptor
        self.encoders[descriptor.codec_id] = descriptor

    def register_demuxer(self, descriptor: ContainerDescriptor):
        self.demuxers[descriptor.name] = descriptor

    def register_muxer(self, descriptor: ContainerDescriptor):
        self.muxers[descriptor.name] = descriptor

    def probe_format_by_extension(self, filename: str) -> Optional[ContainerDescriptor]:
        ext = os.path.splitext(filename)[1].lower().lstrip(".")
        for demuxer in self.demuxers.values():
            if ext in demuxer.extensions:
                return demuxer
        return None

    def find_decoder(self, codec_id: str) -> Optional[CodecDescriptor]:
        return self.decoders.get(codec_id.lower())

    def find_encoder(self, name_or_id: str) -> Optional[CodecDescriptor]:
        return self.encoders.get(name_or_id.lower())


# ============================================================================
# 3. 5-Stage Pipeline Core (Demux -> Decode -> Filter -> Encode -> Mux)
# ============================================================================

class Demuxer:
    """Stage 1: Container Reader (libavformat) extracting compressed AVPackets."""
    def __init__(self, filename: str, registry: CodecContainerRegistry):
        self.filename = filename
        self.container_desc = registry.probe_format_by_extension(filename)
        self.packet_count = 0
        self.max_packets = 5

    def read_packet(self) -> Optional[AVPacket]:
        if self.packet_count >= self.max_packets:
            return None
        pts = self.packet_count * 3000
        dts = pts
        payload = f"COMPRESSED_FRAME_{self.packet_count}".encode('utf-8')
        is_key = (self.packet_count % 3 == 0)
        pkt = AVPacket(stream_index=0, pts=pts, dts=dts, data=payload, is_keyframe=is_key)
        self.packet_count += 1
        return pkt


class Decoder:
    """Stage 2: Codec Decoder (libavcodec) expanding AVPacket into raw AVFrame."""
    def __init__(self, codec_id: str, registry: CodecContainerRegistry, width=1920, height=1080):
        self.codec_desc = registry.find_decoder(codec_id)
        self.width = width
        self.height = height

    def send_packet(self, pkt: AVPacket) -> Optional[AVFrame]:
        if not pkt:
            return None
        frame = AVFrame(
            width=self.width,
            height=self.height,
            pixel_format="yuv420p",
            pts=pkt.pts
        )
        return frame


class FilterNode:
    """Base class for filter graph transformation nodes (libavfilter)."""
    def __init__(self, name: str, params: Dict[str, str]):
        self.name = name
        self.params = params

    def process(self, frame: AVFrame) -> AVFrame:
        return frame


class ScaleFilterNode(FilterNode):
    """Resizes video frame dimensions (libswscale wrapper node)."""
    def process(self, frame: AVFrame) -> AVFrame:
        w = int(self.params.get("w", frame.width))
        h = int(self.params.get("h", frame.height))
        new_frame = AVFrame(
            width=w,
            height=h,
            pixel_format=frame.pixel_format,
            pts=frame.pts
        )
        return new_frame


class CropFilterNode(FilterNode):
    """Crops video frame dimensions."""
    def process(self, frame: AVFrame) -> AVFrame:
        w = int(self.params.get("w", frame.width // 2))
        h = int(self.params.get("h", frame.height // 2))
        return AVFrame(width=w, height=h, pixel_format=frame.pixel_format, pts=frame.pts)


class VolumeFilterNode(FilterNode):
    """Adjusts audio sample gains."""
    def process(self, frame: AVFrame) -> AVFrame:
        # Returns modified audio frame
        return frame


class FilterGraph:
    """
    Stage 3: DAG Filter Graph Processor (libavfilter).
    Parses filter graph expressions (e.g. "scale=1280:720,crop=640:480").
    """
    def __init__(self, graph_spec: str = ""):
        self.graph_spec = graph_spec
        self.nodes: List[FilterNode] = []
        self._parse_graph_spec(graph_spec)

    def _parse_graph_spec(self, spec: str):
        if not spec.strip():
            return
        filter_chains = spec.split(",")
        for chain in filter_chains:
            chain = chain.strip()
            if not chain:
                continue
            if "=" in chain:
                name, param_str = chain.split("=", 1)
                params = {}
                if ":" in param_str:
                    parts = param_str.split(":")
                    if name == "scale" and len(parts) >= 2:
                        params["w"], params["h"] = parts[0], parts[1]
                    elif name == "crop" and len(parts) >= 2:
                        params["w"], params["h"] = parts[0], parts[1]
                else:
                    params["val"] = param_str
            else:
                name = chain
                params = {}

            if name == "scale":
                self.nodes.append(ScaleFilterNode(name, params))
            elif name == "crop":
                self.nodes.append(CropFilterNode(name, params))
            elif name == "volume":
                self.nodes.append(VolumeFilterNode(name, params))

    def process_frame(self, frame: AVFrame) -> AVFrame:
        current = frame
        for node in self.nodes:
            current = node.process(current)
        return current


class Encoder:
    """Stage 4: Codec Encoder (libavcodec) compressing raw AVFrame into AVPacket."""
    def __init__(self, encoder_name: str, registry: CodecContainerRegistry):
        self.encoder_desc = registry.find_encoder(encoder_name)
        self.encoded_count = 0

    def send_frame(self, frame: AVFrame) -> Optional[AVPacket]:
        if not frame:
            return None
        payload = f"ENCODED_{self.encoder_desc.codec_id if self.encoder_desc else 'RAW'}_{frame.width}x{frame.height}_PTS_{frame.pts}".encode('utf-8')
        pkt = AVPacket(
            stream_index=0,
            pts=frame.pts,
            dts=frame.pts,
            data=payload,
            is_keyframe=(self.encoded_count % 3 == 0)
        )
        self.encoded_count += 1
        return pkt


class Muxer:
    """Stage 5: Container Writer (libavformat) writing AVPackets to output file."""
    def __init__(self, filename: str, registry: CodecContainerRegistry):
        self.filename = filename
        self.written_packets: List[AVPacket] = []

    def write_packet(self, pkt: AVPacket) -> bool:
        if not pkt:
            return False
        self.written_packets.append(pkt.clone())
        return True


# ============================================================================
# 4. Pipeline Orchestration & CLI Translator
# ============================================================================

class FFmpegPipeline:
    """
    Orchestrates the 5-stage media transcode loop.
    """
    def __init__(
        self,
        input_filename: str,
        output_filename: str,
        video_codec: str = "libx264",
        filter_spec: str = "",
        registry: Optional[CodecContainerRegistry] = None
    ):
        self.registry = registry if registry else CodecContainerRegistry()
        self.demuxer = Demuxer(input_filename, self.registry)
        self.decoder = Decoder("h264", self.registry)
        self.filter_graph = FilterGraph(filter_spec)
        self.encoder = Encoder(video_codec, self.registry)
        self.muxer = Muxer(output_filename, self.registry)

    def run(self) -> int:
        """Executes full 5-stage loop until end of stream."""
        frames_processed = 0
        while True:
            # 1. Demux
            pkt = self.demuxer.read_packet()
            if not pkt:
                break

            # 2. Decode
            frame = self.decoder.send_packet(pkt)
            if not frame:
                continue

            # 3. Filter
            filtered_frame = self.filter_graph.process_frame(frame)

            # 4. Encode
            enc_pkt = self.encoder.send_frame(filtered_frame)

            # 5. Mux
            if enc_pkt:
                self.muxer.write_packet(enc_pkt)
                frames_processed += 1

        return frames_processed


class FFmpegCLITranslator:
    """
    Parses CLI command string expressions into an executed FFmpegPipeline.
    Example: 'ffmpeg -i input.mp4 -vf scale=1280:720 -c:v libx264 output.mkv'
    """
    def __init__(self, registry: Optional[CodecContainerRegistry] = None):
        self.registry = registry if registry else CodecContainerRegistry()

    def parse_and_execute(self, command_line: str) -> Tuple[FFmpegPipeline, int]:
        tokens = command_line.strip().split()
        if not tokens or tokens[0] != "ffmpeg":
            raise ValueError("Command must start with 'ffmpeg'")

        input_file = ""
        output_file = ""
        video_codec = "libx264"
        filter_spec = ""

        i = 1
        while i < len(tokens):
            tok = tokens[i]
            if tok == "-i" and i + 1 < len(tokens):
                input_file = tokens[i + 1]
                i += 2
            elif tok in ("-vf", "-filter:v", "-filter_complex") and i + 1 < len(tokens):
                filter_spec = tokens[i + 1]
                i += 2
            elif tok in ("-c:v", "-vcodec", "-codec:v") and i + 1 < len(tokens):
                video_codec = tokens[i + 1]
                i += 2
            elif not tok.startswith("-") and i == len(tokens) - 1:
                output_file = tok
                i += 1
            else:
                i += 1

        if not input_file or not output_file:
            raise ValueError("CLI command missing input or output file specifier")

        pipeline = FFmpegPipeline(
            input_filename=input_file,
            output_filename=output_file,
            video_codec=video_codec,
            filter_spec=filter_spec,
            registry=self.registry
        )
        processed = pipeline.run()
        return pipeline, processed
